const allPlayers = [
  // Categoria 1
  {
    player: 'Sacchetti',
    clearWins: 12,
    narrowWins: 2,
    goldenGoalWins: 0,
    losses: 2,
    narrowLosses: 2,
    draws: 0,
    category: 1,
  },
  {
    player: 'Fanna',
    clearWins: 8,
    narrowWins: 1,
    goldenGoalWins: 1,
    losses: 6,
    narrowLosses: 2,
    draws: 1,
    category: 1,
  },
  {
    player: 'Scirea',
    clearWins: 7,
    narrowWins: 3,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 3,
    draws: 2,
    category: 1,
  },
  {
    player: 'Maniero',
    clearWins: 8,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 8,
    narrowLosses: 1,
    draws: 1,
    category: 1,
  },
  {
    player: 'Caprile',
    clearWins: 6,
    narrowWins: 5,
    goldenGoalWins: 2,
    losses: 3,
    narrowLosses: 1,
    draws: 1,
    category: 1,
  },
  {
    player: 'Ingesson',
    clearWins: 7,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 5,
    narrowLosses: 2,
    draws: 1,
    category: 1,
  },
  {
    player: 'Maccarone',
    clearWins: 5,
    narrowWins: 4,
    goldenGoalWins: 1,
    losses: 4,
    narrowLosses: 1,
    draws: 1,
    category: 1,
  },
  {
    player: 'Binotto',
    clearWins: 6,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 9,
    narrowLosses: 0,
    draws: 0,
    category: 1,
  },
  {
    player: "Grighera'",
    clearWins: 4,
    narrowWins: 3,
    goldenGoalWins: 1,
    losses: 3,
    narrowLosses: 2,
    draws: 2,
    category: 1,
  },
  {
    player: 'Miccoli',
    clearWins: 6,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 6,
    narrowLosses: 3,
    draws: 1,
    category: 1,
  },
  {
    player: 'Pizzaballa',
    clearWins: 4,
    narrowWins: 2,
    goldenGoalWins: 2,
    losses: 8,
    narrowLosses: 2,
    draws: 0,
    category: 1,
  },
  {
    player: 'Giannicchedda',
    clearWins: 4,
    narrowWins: 3,
    goldenGoalWins: 0,
    losses: 5,
    narrowLosses: 2,
    draws: 1,
    category: 1,
  },
  {
    player: 'Pjanic',
    clearWins: 3,
    narrowWins: 3,
    goldenGoalWins: 1,
    losses: 2,
    narrowLosses: 1,
    draws: 1,
    category: 1,
  },
  {
    player: 'Marchisio',
    clearWins: 5,
    narrowWins: 3,
    goldenGoalWins: 0,
    losses: 4,
    narrowLosses: 3,
    draws: 1,
    category: 1,
  },
  {
    player: 'Gilardino',
    clearWins: 2,
    narrowWins: 2,
    goldenGoalWins: 1,
    losses: 5,
    narrowLosses: 1,
    draws: 2,
    category: 1,
  },

  // Categoria 2
  {
    player: 'Higuita',
    clearWins: 9,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 4,
    narrowLosses: 1,
    draws: 0,
    category: 2,
  },
  {
    player: 'Nela',
    clearWins: 8,
    narrowWins: 2,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 0,
    draws: 1,
    category: 2,
  },
  {
    player: 'Stellone',
    clearWins: 6,
    narrowWins: 1,
    goldenGoalWins: 1,
    losses: 5,
    narrowLosses: 1,
    draws: 1,
    category: 2,
  },
  {
    player: 'Carrera',
    clearWins: 4,
    narrowWins: 3,
    goldenGoalWins: 2,
    losses: 2,
    narrowLosses: 2,
    draws: 1,
    category: 2,
  },
  {
    player: 'Ambrosini',
    clearWins: 5,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 0,
    draws: 2,
    category: 2,
  },
  {
    player: 'Boniek',
    clearWins: 6,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 8,
    narrowLosses: 1,
    draws: 1,
    category: 2,
  },
  {
    player: 'Mazzarri',
    clearWins: 5,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 9,
    narrowLosses: 3,
    draws: 1,
    category: 2,
  },
  {
    player: 'Georgatos',
    clearWins: 5,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 9,
    narrowLosses: 3,
    draws: 1,
    category: 2,
  },
  {
    player: 'Falcao',
    clearWins: 4,
    narrowWins: 2,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 0,
    draws: 0,
    category: 2,
  },
  {
    player: 'Abate',
    clearWins: 1,
    narrowWins: 3,
    goldenGoalWins: 0,
    losses: 1,
    narrowLosses: 1,
    draws: 1,
    category: 2,
  },
  {
    player: 'Amelia',
    clearWins: 2,
    narrowWins: 2,
    goldenGoalWins: 0,
    losses: 2,
    narrowLosses: 2,
    draws: 1,
    category: 2,
  },
  {
    player: 'Rugani',
    clearWins: 1,
    narrowWins: 2,
    goldenGoalWins: 1,
    losses: 7,
    narrowLosses: 1,
    draws: 1,
    category: 2,
  },
  {
    player: 'Delpiero',
    clearWins: 1,
    narrowWins: 1,
    goldenGoalWins: 1,
    losses: 8,
    narrowLosses: 0,
    draws: 0,
    category: 2,
  },

  // Categoria 3
  {
    player: 'Marchetti',
    clearWins: 2,
    narrowWins: 2,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 4,
    draws: 1,
    category: 3,
  },
  {
    player: 'Bergomi',
    clearWins: 5,
    narrowWins: 1,
    goldenGoalWins: 1,
    losses: 5,
    narrowLosses: 2,
    draws: 0,
    category: 3,
  },
  {
    player: 'Mancini',
    clearWins: 3,
    narrowWins: 3,
    goldenGoalWins: 1,
    losses: 1,
    narrowLosses: 2,
    draws: 2,
    category: 3,
  },
  {
    player: 'Rampulla',
    clearWins: 4,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 8,
    narrowLosses: 2,
    draws: 1,
    category: 3,
  },
  {
    player: 'Littbarski',
    clearWins: 3,
    narrowWins: 0,
    goldenGoalWins: 1,
    losses: 6,
    narrowLosses: 3,
    draws: 2,
    category: 3,
  },
  {
    player: 'Moscardelli',
    clearWins: 2,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 7,
    narrowLosses: 3,
    draws: 1,
    category: 3,
  },
  {
    player: 'Destro',
    clearWins: 3,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 4,
    narrowLosses: 2,
    draws: 1,
    category: 3,
  },
  {
    player: 'Mhattaus',
    clearWins: 4,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 6,
    narrowLosses: 0,
    draws: 0,
    category: 3,
  },
  {
    player: 'Adriano',
    clearWins: 3,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 4,
    narrowLosses: 0,
    draws: 1,
    category: 3,
  },
  {
    player: 'Strootman',
    clearWins: 0,
    narrowWins: 1,
    goldenGoalWins: 1,
    losses: 3,
    narrowLosses: 3,
    draws: 1,
    category: 3,
  },
  {
    player: 'Vicario',
    clearWins: 1,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 2,
    narrowLosses: 0,
    draws: 1,
    category: 3,
  },
  {
    player: 'Galante',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 3,
  },
  {
    player: 'Rapayc',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 3,
  },
  {
    player: 'Ichazo',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 3,
  },

  // Categoria 4
  {
    player: "Benzema'",
    clearWins: 6,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 1,
    narrowLosses: 2,
    draws: 1,
    category: 4,
  },
  {
    player: 'Buongiorno',
    clearWins: 2,
    narrowWins: 3,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 4,
    draws: 2,
    category: 4,
  },
  {
    player: 'Frey',
    clearWins: 3,
    narrowWins: 0,
    goldenGoalWins: 1,
    losses: 1,
    narrowLosses: 3,
    draws: 1,
    category: 4,
  },
  {
    player: 'Roonney',
    clearWins: 2,
    narrowWins: 1,
    goldenGoalWins: 2,
    losses: 0,
    narrowLosses: 2,
    draws: 1,
    category: 4,
  },
  {
    player: 'Benji',
    clearWins: 3,
    narrowWins: 1,
    goldenGoalWins: 1,
    losses: 1,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Salah',
    clearWins: 1,
    narrowWins: 2,
    goldenGoalWins: 1,
    losses: 2,
    narrowLosses: 0,
    draws: 1,
    category: 4,
  },
  {
    player: 'Cucureddu',
    clearWins: 2,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Neuer',
    clearWins: 1,
    narrowWins: 1,
    goldenGoalWins: 1,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Bastoni',
    clearWins: 1,
    narrowWins: 1,
    goldenGoalWins: 1,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Gallotto',
    clearWins: 2,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 4,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Darmian',
    clearWins: 1,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 1,
    narrowLosses: 1,
    draws: 0,
    category: 4,
  },
  {
    player: 'Courtois',
    clearWins: 1,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 0,
    draws: 1,
    category: 4,
  },
  {
    player: 'Protti',
    clearWins: 0,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 1,
    narrowLosses: 3,
    draws: 0,
    category: 4,
  },
  {
    player: 'Samardic',
    clearWins: 1,
    narrowWins: 0,
    goldenGoalWins: 1,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Carmignani',
    clearWins: 1,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Benarrivo',
    clearWins: 1,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Vierchowod',
    clearWins: 1,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 2,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Delapena',
    clearWins: 1,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 1,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Barella',
    clearWins: 1,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Chiesa',
    clearWins: 0,
    narrowWins: 1,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 1,
    draws: 0,
    category: 4,
  },
  {
    player: 'Pepe',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 1,
    draws: 1,
    category: 4,
  },
  {
    player: 'Simon',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 1,
    draws: 0,
    category: 4,
  },
  {
    player: 'Liverani',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 1,
    draws: 0,
    category: 4,
  },
  {
    player: 'Vucinic',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Baresi',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Deketelare',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 1,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Tavarilli',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Zaza',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 3,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Modric',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Benali',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Taglialatela',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 1,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'West',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 0,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
  {
    player: 'Sanchez',
    clearWins: 0,
    narrowWins: 0,
    goldenGoalWins: 0,
    losses: 1,
    narrowLosses: 0,
    draws: 0,
    category: 4,
  },
];

export default allPlayers;
